Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,45 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/reference/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
+  build-and-compile:
     docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
-      - image: cimg/base:current
-
-    # Add steps to the job
-    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
+      - image: ubuntu:24.04
+    
     steps:
-      # Checkout the code as the first step.
       - checkout
+      
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Install dependencies
+          command: |
+            apt-get update
+            apt-get install -y build-essential cmake libsfml-dev
+      
+      - run:
+          name: Configure with CMake
+          command: |
+            mkdir build
+            cd build
+            cmake ..
+      
+      - run:
+          name: Compile project
+          command: |
+            cd build
+            make -j$(nproc)
+      
+      - run:
+          name: Verify build succeeded
+          command: |
+            if [ -f "build/Pacman_Retry" ]; then
+              echo "✓ Build successful - executable created"
+              ls -lh build/Pacman_Retry
+            else
+              echo "✗ Build failed - executable not found"
+              exit 1
+            fi
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  version: 2
+  build-workflow:
     jobs:
-      - say-hello
+      - build-and-compile
